// llmenum.go 由 OpenAPI 的 LLMEnumPublic 生成（2026-10-07）—— **不要手改**。
//
// 上游 `operations/agent-map` 的 `llm` 参数共有 143 个枚举值，覆盖 33 个模型家族
// （GPT-5.x / Claude 4.5~5.5 / Gemini 3.x / Grok / GLM / Muse Spark），每个家族带
// NT/LOW/MEDIUM/HIGH/XHIGH/MAX 等推理档。
//
// 模型名规则：`GPT_5_6_TERRA_HIGH` → `gpt-5.6-terra-high`。
// 用这些模型 = **显式指定底层模型 + iteration_budget=0**（单次调用、不做多轮研究）；
// 想要研究迭代就用 `agent-*` / `multi-agent-*` 预设。
//
// 生成方式：读 https://futuresearch.ai/api/v0/openapi.json 的
// components.schemas.LLMEnumPublic.enum，按上面规则转 slug。
package fsapi

// llmModel 一个上游 llm 枚举值。
type llmModel struct {
	Slug  string // 模型名（不含渠道前缀）
	Label string // 展示名
	Enum  string // 上游枚举原文
}

// llmModels 全部 143 个枚举。
var llmModels = []llmModel{
	{Slug: "gpt-5", Label: "GPT-5", Enum: "GPT_5"},
	{Slug: "gpt-5-minimal", Label: "GPT-5 Minimal", Enum: "GPT_5_MINIMAL"},
	{Slug: "gpt-5-low", Label: "GPT-5 Low", Enum: "GPT_5_LOW"},
	{Slug: "gpt-5-high", Label: "GPT-5 High", Enum: "GPT_5_HIGH"},
	{Slug: "gpt-5-mini", Label: "GPT-5 Mini", Enum: "GPT_5_MINI"},
	{Slug: "gpt-5-nano", Label: "GPT-5 Nano", Enum: "GPT_5_NANO"},
	{Slug: "gpt-5.1-nt", Label: "GPT-5.1 NT", Enum: "GPT_5_1_NT"},
	{Slug: "gpt-5.1-low", Label: "GPT-5.1 Low", Enum: "GPT_5_1_LOW"},
	{Slug: "gpt-5.2-nt", Label: "GPT-5.2 NT", Enum: "GPT_5_2_NT"},
	{Slug: "gpt-5.2-low", Label: "GPT-5.2 Low", Enum: "GPT_5_2_LOW"},
	{Slug: "gpt-5.2-medium", Label: "GPT-5.2 Medium", Enum: "GPT_5_2_MEDIUM"},
	{Slug: "gpt-5.2-high", Label: "GPT-5.2 High", Enum: "GPT_5_2_HIGH"},
	{Slug: "gpt-5.4-nt", Label: "GPT-5.4 NT", Enum: "GPT_5_4_NT"},
	{Slug: "gpt-5.4-low", Label: "GPT-5.4 Low", Enum: "GPT_5_4_LOW"},
	{Slug: "gpt-5.4-medium", Label: "GPT-5.4 Medium", Enum: "GPT_5_4_MEDIUM"},
	{Slug: "gpt-5.4-high", Label: "GPT-5.4 High", Enum: "GPT_5_4_HIGH"},
	{Slug: "gpt-5.4-xhigh", Label: "GPT-5.4 XHigh", Enum: "GPT_5_4_XHIGH"},
	{Slug: "gpt-5.4-pro-medium", Label: "GPT-5.4 Pro Medium", Enum: "GPT_5_4_PRO_MEDIUM"},
	{Slug: "gpt-5.4-pro-high", Label: "GPT-5.4 Pro High", Enum: "GPT_5_4_PRO_HIGH"},
	{Slug: "gpt-5.4-pro-xhigh", Label: "GPT-5.4 Pro XHigh", Enum: "GPT_5_4_PRO_XHIGH"},
	{Slug: "gpt-5.4-mini-nt", Label: "GPT-5.4 Mini NT", Enum: "GPT_5_4_MINI_NT"},
	{Slug: "gpt-5.4-mini-low", Label: "GPT-5.4 Mini Low", Enum: "GPT_5_4_MINI_LOW"},
	{Slug: "gpt-5.4-mini-medium", Label: "GPT-5.4 Mini Medium", Enum: "GPT_5_4_MINI_MEDIUM"},
	{Slug: "gpt-5.4-mini-high", Label: "GPT-5.4 Mini High", Enum: "GPT_5_4_MINI_HIGH"},
	{Slug: "gpt-5.4-nano-nt", Label: "GPT-5.4 Nano NT", Enum: "GPT_5_4_NANO_NT"},
	{Slug: "gpt-5.4-nano-low", Label: "GPT-5.4 Nano Low", Enum: "GPT_5_4_NANO_LOW"},
	{Slug: "gpt-5.4-nano-medium", Label: "GPT-5.4 Nano Medium", Enum: "GPT_5_4_NANO_MEDIUM"},
	{Slug: "gpt-5.4-nano-high", Label: "GPT-5.4 Nano High", Enum: "GPT_5_4_NANO_HIGH"},
	{Slug: "gpt-5.5-nt", Label: "GPT-5.5 NT", Enum: "GPT_5_5_NT"},
	{Slug: "gpt-5.5-low", Label: "GPT-5.5 Low", Enum: "GPT_5_5_LOW"},
	{Slug: "gpt-5.5-medium", Label: "GPT-5.5 Medium", Enum: "GPT_5_5_MEDIUM"},
	{Slug: "gpt-5.5-high", Label: "GPT-5.5 High", Enum: "GPT_5_5_HIGH"},
	{Slug: "gpt-5.5-xhigh", Label: "GPT-5.5 XHigh", Enum: "GPT_5_5_XHIGH"},
	{Slug: "gpt-5.6-sol-nt", Label: "GPT-5.6 Sol NT", Enum: "GPT_5_6_SOL_NT"},
	{Slug: "gpt-5.6-sol-low", Label: "GPT-5.6 Sol Low", Enum: "GPT_5_6_SOL_LOW"},
	{Slug: "gpt-5.6-sol-medium", Label: "GPT-5.6 Sol Medium", Enum: "GPT_5_6_SOL_MEDIUM"},
	{Slug: "gpt-5.6-sol-high", Label: "GPT-5.6 Sol High", Enum: "GPT_5_6_SOL_HIGH"},
	{Slug: "gpt-5.6-sol-xhigh", Label: "GPT-5.6 Sol XHigh", Enum: "GPT_5_6_SOL_XHIGH"},
	{Slug: "gpt-5.6-sol-max", Label: "GPT-5.6 Sol Max", Enum: "GPT_5_6_SOL_MAX"},
	{Slug: "gpt-5.6-terra-nt", Label: "GPT-5.6 Terra NT", Enum: "GPT_5_6_TERRA_NT"},
	{Slug: "gpt-5.6-terra-low", Label: "GPT-5.6 Terra Low", Enum: "GPT_5_6_TERRA_LOW"},
	{Slug: "gpt-5.6-terra-medium", Label: "GPT-5.6 Terra Medium", Enum: "GPT_5_6_TERRA_MEDIUM"},
	{Slug: "gpt-5.6-terra-high", Label: "GPT-5.6 Terra High", Enum: "GPT_5_6_TERRA_HIGH"},
	{Slug: "gpt-5.6-terra-xhigh", Label: "GPT-5.6 Terra XHigh", Enum: "GPT_5_6_TERRA_XHIGH"},
	{Slug: "gpt-5.6-terra-max", Label: "GPT-5.6 Terra Max", Enum: "GPT_5_6_TERRA_MAX"},
	{Slug: "gpt-5.6-luna-nt", Label: "GPT-5.6 Luna NT", Enum: "GPT_5_6_LUNA_NT"},
	{Slug: "gpt-5.6-luna-low", Label: "GPT-5.6 Luna Low", Enum: "GPT_5_6_LUNA_LOW"},
	{Slug: "gpt-5.6-luna-medium", Label: "GPT-5.6 Luna Medium", Enum: "GPT_5_6_LUNA_MEDIUM"},
	{Slug: "gpt-5.6-luna-high", Label: "GPT-5.6 Luna High", Enum: "GPT_5_6_LUNA_HIGH"},
	{Slug: "gpt-5.6-luna-xhigh", Label: "GPT-5.6 Luna XHigh", Enum: "GPT_5_6_LUNA_XHIGH"},
	{Slug: "gpt-5.6-luna-max", Label: "GPT-5.6 Luna Max", Enum: "GPT_5_6_LUNA_MAX"},
	{Slug: "gpt-6-astra-low", Label: "GPT-6 Astra Low", Enum: "GPT_6_ASTRA_LOW"},
	{Slug: "gpt-6-astra-medium", Label: "GPT-6 Astra Medium", Enum: "GPT_6_ASTRA_MEDIUM"},
	{Slug: "gpt-6-astra-high", Label: "GPT-6 Astra High", Enum: "GPT_6_ASTRA_HIGH"},
	{Slug: "gpt-6-astra-xhigh", Label: "GPT-6 Astra XHigh", Enum: "GPT_6_ASTRA_XHIGH"},
	{Slug: "gpt-6-astra-max", Label: "GPT-6 Astra Max", Enum: "GPT_6_ASTRA_MAX"},
	{Slug: "gpt-6.1-sol-low", Label: "GPT-6.1 Sol Low", Enum: "GPT_6_1_SOL_LOW"},
	{Slug: "gpt-6.1-sol-medium", Label: "GPT-6.1 Sol Medium", Enum: "GPT_6_1_SOL_MEDIUM"},
	{Slug: "gpt-6.1-sol-high", Label: "GPT-6.1 Sol High", Enum: "GPT_6_1_SOL_HIGH"},
	{Slug: "gpt-6.1-sol-xhigh", Label: "GPT-6.1 Sol XHigh", Enum: "GPT_6_1_SOL_XHIGH"},
	{Slug: "gpt-6.1-sol-max", Label: "GPT-6.1 Sol Max", Enum: "GPT_6_1_SOL_MAX"},
	{Slug: "claude-4.5-sonnet", Label: "Claude-4.5 Sonnet", Enum: "CLAUDE_4_5_SONNET"},
	{Slug: "claude-4.5-sonnet-thinking", Label: "Claude-4.5 Sonnet Thinking", Enum: "CLAUDE_4_5_SONNET_THINKING"},
	{Slug: "claude-4.5-sonnet-high", Label: "Claude-4.5 Sonnet High", Enum: "CLAUDE_4_5_SONNET_HIGH"},
	{Slug: "claude-4.5-sonnet-minimal", Label: "Claude-4.5 Sonnet Minimal", Enum: "CLAUDE_4_5_SONNET_MINIMAL"},
	{Slug: "claude-4.5-haiku", Label: "Claude-4.5 Haiku", Enum: "CLAUDE_4_5_HAIKU"},
	{Slug: "claude-4.5-haiku-thinking", Label: "Claude-4.5 Haiku Thinking", Enum: "CLAUDE_4_5_HAIKU_THINKING"},
	{Slug: "claude-4.5-haiku-minimal", Label: "Claude-4.5 Haiku Minimal", Enum: "CLAUDE_4_5_HAIKU_MINIMAL"},
	{Slug: "claude-4.5-opus", Label: "Claude-4.5 Opus", Enum: "CLAUDE_4_5_OPUS"},
	{Slug: "claude-4.5-opus-thinking", Label: "Claude-4.5 Opus Thinking", Enum: "CLAUDE_4_5_OPUS_THINKING"},
	{Slug: "claude-4.5-opus-low", Label: "Claude-4.5 Opus Low", Enum: "CLAUDE_4_5_OPUS_LOW"},
	{Slug: "claude-4.5-opus-high", Label: "Claude-4.5 Opus High", Enum: "CLAUDE_4_5_OPUS_HIGH"},
	{Slug: "claude-4.6-opus-nt", Label: "Claude-4.6 Opus NT", Enum: "CLAUDE_4_6_OPUS_NT"},
	{Slug: "claude-4.6-opus-low", Label: "Claude-4.6 Opus Low", Enum: "CLAUDE_4_6_OPUS_LOW"},
	{Slug: "claude-4.6-opus-medium", Label: "Claude-4.6 Opus Medium", Enum: "CLAUDE_4_6_OPUS_MEDIUM"},
	{Slug: "claude-4.6-opus-high", Label: "Claude-4.6 Opus High", Enum: "CLAUDE_4_6_OPUS_HIGH"},
	{Slug: "claude-4.6-opus-max", Label: "Claude-4.6 Opus Max", Enum: "CLAUDE_4_6_OPUS_MAX"},
	{Slug: "claude-4.6-sonnet-nt", Label: "Claude-4.6 Sonnet NT", Enum: "CLAUDE_4_6_SONNET_NT"},
	{Slug: "claude-4.6-sonnet-low", Label: "Claude-4.6 Sonnet Low", Enum: "CLAUDE_4_6_SONNET_LOW"},
	{Slug: "claude-4.6-sonnet-medium", Label: "Claude-4.6 Sonnet Medium", Enum: "CLAUDE_4_6_SONNET_MEDIUM"},
	{Slug: "claude-4.6-sonnet-high", Label: "Claude-4.6 Sonnet High", Enum: "CLAUDE_4_6_SONNET_HIGH"},
	{Slug: "claude-4.6-sonnet-max", Label: "Claude-4.6 Sonnet Max", Enum: "CLAUDE_4_6_SONNET_MAX"},
	{Slug: "claude-4.7-opus-nt", Label: "Claude-4.7 Opus NT", Enum: "CLAUDE_4_7_OPUS_NT"},
	{Slug: "claude-4.7-opus-low", Label: "Claude-4.7 Opus Low", Enum: "CLAUDE_4_7_OPUS_LOW"},
	{Slug: "claude-4.7-opus-medium", Label: "Claude-4.7 Opus Medium", Enum: "CLAUDE_4_7_OPUS_MEDIUM"},
	{Slug: "claude-4.7-opus-high", Label: "Claude-4.7 Opus High", Enum: "CLAUDE_4_7_OPUS_HIGH"},
	{Slug: "claude-4.7-opus-max", Label: "Claude-4.7 Opus Max", Enum: "CLAUDE_4_7_OPUS_MAX"},
	{Slug: "claude-4.8-opus-nt", Label: "Claude-4.8 Opus NT", Enum: "CLAUDE_4_8_OPUS_NT"},
	{Slug: "claude-4.8-opus-low", Label: "Claude-4.8 Opus Low", Enum: "CLAUDE_4_8_OPUS_LOW"},
	{Slug: "claude-4.8-opus-medium", Label: "Claude-4.8 Opus Medium", Enum: "CLAUDE_4_8_OPUS_MEDIUM"},
	{Slug: "claude-4.8-opus-high", Label: "Claude-4.8 Opus High", Enum: "CLAUDE_4_8_OPUS_HIGH"},
	{Slug: "claude-4.8-opus-xhigh", Label: "Claude-4.8 Opus XHigh", Enum: "CLAUDE_4_8_OPUS_XHIGH"},
	{Slug: "claude-4.8-opus-max", Label: "Claude-4.8 Opus Max", Enum: "CLAUDE_4_8_OPUS_MAX"},
	{Slug: "claude-fable-5-nt", Label: "Claude Fable-5 NT", Enum: "CLAUDE_FABLE_5_NT"},
	{Slug: "claude-fable-5-low", Label: "Claude Fable-5 Low", Enum: "CLAUDE_FABLE_5_LOW"},
	{Slug: "claude-fable-5-medium", Label: "Claude Fable-5 Medium", Enum: "CLAUDE_FABLE_5_MEDIUM"},
	{Slug: "claude-fable-5-high", Label: "Claude Fable-5 High", Enum: "CLAUDE_FABLE_5_HIGH"},
	{Slug: "claude-fable-5-xhigh", Label: "Claude Fable-5 XHigh", Enum: "CLAUDE_FABLE_5_XHIGH"},
	{Slug: "claude-fable-5-max", Label: "Claude Fable-5 Max", Enum: "CLAUDE_FABLE_5_MAX"},
	{Slug: "claude-5-sonnet-nt", Label: "Claude-5 Sonnet NT", Enum: "CLAUDE_5_SONNET_NT"},
	{Slug: "claude-5-sonnet-low", Label: "Claude-5 Sonnet Low", Enum: "CLAUDE_5_SONNET_LOW"},
	{Slug: "claude-5-sonnet-medium", Label: "Claude-5 Sonnet Medium", Enum: "CLAUDE_5_SONNET_MEDIUM"},
	{Slug: "claude-5-sonnet-high", Label: "Claude-5 Sonnet High", Enum: "CLAUDE_5_SONNET_HIGH"},
	{Slug: "claude-5-sonnet-xhigh", Label: "Claude-5 Sonnet XHigh", Enum: "CLAUDE_5_SONNET_XHIGH"},
	{Slug: "claude-5-sonnet-max", Label: "Claude-5 Sonnet Max", Enum: "CLAUDE_5_SONNET_MAX"},
	{Slug: "claude-5-opus-nt", Label: "Claude-5 Opus NT", Enum: "CLAUDE_5_OPUS_NT"},
	{Slug: "claude-5-opus-low", Label: "Claude-5 Opus Low", Enum: "CLAUDE_5_OPUS_LOW"},
	{Slug: "claude-5-opus-medium", Label: "Claude-5 Opus Medium", Enum: "CLAUDE_5_OPUS_MEDIUM"},
	{Slug: "claude-5-opus-high", Label: "Claude-5 Opus High", Enum: "CLAUDE_5_OPUS_HIGH"},
	{Slug: "claude-5-opus-xhigh", Label: "Claude-5 Opus XHigh", Enum: "CLAUDE_5_OPUS_XHIGH"},
	{Slug: "claude-5-opus-max", Label: "Claude-5 Opus Max", Enum: "CLAUDE_5_OPUS_MAX"},
	{Slug: "claude-5.5-opus-low", Label: "Claude-5.5 Opus Low", Enum: "CLAUDE_5_5_OPUS_LOW"},
	{Slug: "claude-5.5-opus-medium", Label: "Claude-5.5 Opus Medium", Enum: "CLAUDE_5_5_OPUS_MEDIUM"},
	{Slug: "claude-5.5-opus-high", Label: "Claude-5.5 Opus High", Enum: "CLAUDE_5_5_OPUS_HIGH"},
	{Slug: "claude-5.5-opus-xhigh", Label: "Claude-5.5 Opus XHigh", Enum: "CLAUDE_5_5_OPUS_XHIGH"},
	{Slug: "claude-5.5-opus-max", Label: "Claude-5.5 Opus Max", Enum: "CLAUDE_5_5_OPUS_MAX"},
	{Slug: "gemini-3.1-pro-low", Label: "Gemini-3.1 Pro Low", Enum: "GEMINI_3_1_PRO_LOW"},
	{Slug: "gemini-3.1-pro-medium", Label: "Gemini-3.1 Pro Medium", Enum: "GEMINI_3_1_PRO_MEDIUM"},
	{Slug: "gemini-3.1-pro-high", Label: "Gemini-3.1 Pro High", Enum: "GEMINI_3_1_PRO_HIGH"},
	{Slug: "gemini-3-flash-minimal", Label: "Gemini-3 Flash Minimal", Enum: "GEMINI_3_FLASH_MINIMAL"},
	{Slug: "gemini-3-flash-low", Label: "Gemini-3 Flash Low", Enum: "GEMINI_3_FLASH_LOW"},
	{Slug: "gemini-3-flash-medium", Label: "Gemini-3 Flash Medium", Enum: "GEMINI_3_FLASH_MEDIUM"},
	{Slug: "gemini-3-flash-high", Label: "Gemini-3 Flash High", Enum: "GEMINI_3_FLASH_HIGH"},
	{Slug: "gemini-3.5-flash-minimal", Label: "Gemini-3.5 Flash Minimal", Enum: "GEMINI_3_5_FLASH_MINIMAL"},
	{Slug: "gemini-3.5-flash-low", Label: "Gemini-3.5 Flash Low", Enum: "GEMINI_3_5_FLASH_LOW"},
	{Slug: "gemini-3.5-flash-medium", Label: "Gemini-3.5 Flash Medium", Enum: "GEMINI_3_5_FLASH_MEDIUM"},
	{Slug: "gemini-3.5-flash-high", Label: "Gemini-3.5 Flash High", Enum: "GEMINI_3_5_FLASH_HIGH"},
	{Slug: "gemini-3.8-flash-minimal", Label: "Gemini-3.8 Flash Minimal", Enum: "GEMINI_3_8_FLASH_MINIMAL"},
	{Slug: "gemini-3.8-flash-low", Label: "Gemini-3.8 Flash Low", Enum: "GEMINI_3_8_FLASH_LOW"},
	{Slug: "gemini-3.8-flash-medium", Label: "Gemini-3.8 Flash Medium", Enum: "GEMINI_3_8_FLASH_MEDIUM"},
	{Slug: "gemini-3.8-flash-high", Label: "Gemini-3.8 Flash High", Enum: "GEMINI_3_8_FLASH_HIGH"},
	{Slug: "gemini-3.5-flash-lite", Label: "Gemini-3.5 Flash Lite", Enum: "GEMINI_3_5_FLASH_LITE"},
	{Slug: "gemini-3.5-flash-lite-low", Label: "Gemini-3.5 Flash Lite Low", Enum: "GEMINI_3_5_FLASH_LITE_LOW"},
	{Slug: "gemini-3.5-flash-lite-medium", Label: "Gemini-3.5 Flash Lite Medium", Enum: "GEMINI_3_5_FLASH_LITE_MEDIUM"},
	{Slug: "gemini-3.5-flash-lite-high", Label: "Gemini-3.5 Flash Lite High", Enum: "GEMINI_3_5_FLASH_LITE_HIGH"},
	{Slug: "muse-spark-minimal", Label: "Muse Spark Minimal", Enum: "MUSE_SPARK_MINIMAL"},
	{Slug: "muse-spark-low", Label: "Muse Spark Low", Enum: "MUSE_SPARK_LOW"},
	{Slug: "muse-spark-medium", Label: "Muse Spark Medium", Enum: "MUSE_SPARK_MEDIUM"},
	{Slug: "muse-spark-high", Label: "Muse Spark High", Enum: "MUSE_SPARK_HIGH"},
	{Slug: "muse-spark-xhigh", Label: "Muse Spark Xhigh", Enum: "MUSE_SPARK_XHIGH"},
	{Slug: "grok-4.5", Label: "Grok-4.5", Enum: "GROK_4_5"},
	{Slug: "glm-5.3-flash", Label: "GLM-5.3 Flash", Enum: "GLM_5_3_FLASH"},
	{Slug: "glm-5.3", Label: "GLM-5.3", Enum: "GLM_5_3"},
}

// llmBySlug slug → 枚举。
var llmBySlug = func() map[string]llmModel {
	m := make(map[string]llmModel, len(llmModels))
	for _, x := range llmModels {
		m[x.Slug] = x
	}
	return m
}()
